version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - koko_network
    volumes:
      - /home/rhgudtjrsla/nginx.conf:/etc/nginx/nginx.conf
      - koko_static:/data/static/
      - koko_media:/data/media/


  django:
    image: koko_django:5
    networks:
      - koko_network
    volumes:
      - koko_static:/home/test33/staticfiles/
      - koko_media:/home/test33/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - koko_network
    volumes:
      - koko_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: 1234
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD

networks:
  koko_network:

volumes:
  koko_static:
  koko_media:
  koko_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true